version: "3"

services:
  hcastserver:
    image: hcast-server
    ports:
      - 5700-5800
    networks:
      - server
    deploy:
      replicas: 2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 6
  hcastclient:
    image: hcast-client
    networks:
      - client
      - server
    depends_on:
      - hcastserver
    ports:
      - 8080:8080
    deploy:
      replicas: 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 6

networks:
  client:
    driver: overlay
  server:
    driver: overlay