server.port: 8010



endpoints:
  autoconfig.enabled: false
  beans.enabled: false
  configprops.enabled: false
  dump.enabled: true
  env.enabled: true
  health.enabled: true
  info.enabled: true
  metrics.enabled: true
  mappings.enabled: false
  shutdown.enabled: false
  trace.enabled: true
  jolokia:
    enabled: true
    path: /jolokia
    sensitive: true

spring:
  data:
    cassandra:
      schema-action: CREATE_IF_NOT_EXISTS
      keyspace-name: star
    jpa:
      repositories:
        enabled: false

---
spring:
  profiles: docker
  data:
    cassandra:
      contact-points: "cassandra"


#---
#spring:
#  profiles: hazelcastmanager
#
#hazelcast:
#  manager-url:
