CREATE TABLE gaia_source ( 
	solution_id bigint,
	source_id bigint primary key,
	random_index bigint,
	ref_epoch double precision,
	ra double precision,
	ra_error double precision,
	dec double precision,
	dec_error double precision,
	parallax double precision,
	parallax_error double precision,
	pmra double precision,
	pmra_error double precision,
	pmdec double precision,
	pmdec_error double precision,
	ra_dec_corr double precision,
	ra_parallax_corr double precision,
	ra_pmra_corr double precision,
	ra_pmdec_corr double precision,
	dec_parallax_corr double precision,
	dec_pmra_corr double precision,
	dec_pmdec_corr double precision,
	parallax_pmra_corr double precision,
	parallax_pmdec_corr double precision,
	pmra_pmdec_corr double precision,
	astrometric_n_obs_al integer,
	astrometric_n_obs_ac integer,
	astrometric_n_good_obs_al integer,
	astrometric_n_good_obs_ac integer,
	astrometric_n_bad_obs_al integer,
	astrometric_n_bad_obs_ac integer,
	astrometric_delta_q double precision,
	astrometric_excess_noise double precision,
	astrometric_excess_noise_sig double precision,
	astrometric_primary_flag boolean,
	astrometric_relegation_factor double precision,
	astrometric_weight_al double precision,
	astrometric_weight_ac double precision,
	astrometric_priors_used integer,
	matched_observations integer,
	duplicated_source boolean,
	scan_direction_strength_k1 double precision,
	scan_direction_strength_k2 double precision,
	scan_direction_strength_k3 double precision,
	scan_direction_strength_k4 double precision,
	scan_direction_mean_k1 double precision,
	scan_direction_mean_k2 double precision,
	scan_direction_mean_k3 double precision,
	scan_direction_mean_k4 double precision,
	phot_g_n_obs integer,
	phot_g_mean_flux double precision,
	phot_g_mean_flux_error double precision,
	phot_g_mean_mag double precision,
	phot_variable_flag varchar(25),
	l double precision,
	b double precision,
	ecl_lon double precision,
	ecl_lat double precision
);
