server.port: 8020

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database-platform: POSTGRESQL
    database: postgresql
#  datasource:
  datasource:
#    hikari:
#      driver-class-name: org.postgresql.Driver
#      jdbc-url: jdbc:postgresql://localhost/gaia
#      password: gaia
#      username: gaia
#      pool-name: gaia
#      datasource
#    username: gaia
#    password: gaia
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost/gaia
    username: gaia
    password: gaia
    driver-class-name: org.postgresql.Driver
    name: gaia

endpoints:
  autoconfig.enabled: false
  beans.enabled: false
  configprops.enabled: false
  dump.enabled: true
  env.enabled: true
  health.enabled: true
  info.enabled: true
  metrics.enabled: true
  mappings.enabled: false
  shutdown.enabled: false
  trace.enabled: true
  jolokia:
    enabled: true
    path: /jolokia
    sensitive: true


---

spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://postgresql/gaia
